apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kzgvzkpfr-python 
  janus-idp.io/tekton: kzgvzkpfr-python
  backstage.io/kubernetes-id: kzgvzkpfr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kzgvzkpfr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml